name: Quality assurance
on:
  workflow_dispatch:
jobs:
  php-unit-tests:
    name: PHP Unit tests
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        php-versions: ["8.0"]
        coverage-driver: [pcov]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: ${{ matrix.coverage-driver }}
          tools: composer:v2
      - name: Packagist.com Auth
        run: composer config --global --auth github-oauth.github.com token ${{ secrets.GA_AUTH }}
      - name: Install composer dependencies (use cache)
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist"
      - name: Run unit tests
        run: ./vendor/bin/phpunit --no-coverage
      - name: Run infection
        run: vendor/bin/infection --min-covered-msi=30 --threads=4 --logger-github --only-covered
